apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: github-pr-ttm-seldon
spec:
  name: github-pr-ttm
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: quay.io/aicoe/github-pr-ttm:latest
          name: github-pr-ttm-clf
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 1000Mi
          env:
          - name: GUNICORN_WORKERS
            value: '1'
          - name: GUNICORN_THREADS
            value: '2'
          - name: S3_ENDPOINT
            valueFrom:
              secretKeyRef:
                key: S3_ENDPOINT
                name: github-pr-ttm-secret
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: S3_ACCESS_KEY
                name: github-pr-ttm-secret
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: S3_SECRET_KEY
                name: github-pr-ttm-secret
          - name: S3_BUCKET
            valueFrom:
              secretKeyRef:
                key: S3_BUCKET
                name: github-pr-ttm-secret
          - name: S3_MODEL_KEY
            valueFrom:
              secretKeyRef:
                key: S3_MODEL_KEY
                name: github-pr-ttm-secret
    svcOrchSpec:
      resources:
        requests:
          cpu: 100m
          memory: 250Mi
        limits:
          cpu: 500m
          memory: 500Mi
    graph:
      children: []
      endpoint:
        type: REST
      name: github-pr-ttm-clf
      type: MODEL
    name: github-pr-ttm-predictor
    replicas: 1
